#!/usr/bin/env bash

set -euf -o pipefail

root_dir="$(cd "$(dirname "$0")/.." && pwd)"

# shellcheck source=../helpers/utils.sh
source "$root_dir/helpers/utils.sh"

echo "Installing tpm..."
mkdir -p ~/.tmux/plugins/
if [[ ! -d ~/.tmux/plugins/tpm ]]; then
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

echo "Installing tmux plugins..."
~/.tmux/plugins/tpm/bin/install_plugins
~/.tmux/plugins/tpm/bin/update_plugins all
~/.tmux/plugins/tpm/bin/clean_plugins
